/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as NoauthImport } from "./routes/_noauth";
import { Route as AuthImport } from "./routes/_auth";
import { Route as NoauthSigninImport } from "./routes/_noauth/signin";
import { Route as AuthDashboardImport } from "./routes/_auth/dashboard";

// Create/Update Routes

const NoauthRoute = NoauthImport.update({
  id: "/_noauth",
  getParentRoute: () => rootRoute,
} as any);

const AuthRoute = AuthImport.update({
  id: "/_auth",
  getParentRoute: () => rootRoute,
} as any);

const NoauthSigninRoute = NoauthSigninImport.update({
  path: "/signin",
  getParentRoute: () => NoauthRoute,
} as any);

const AuthDashboardRoute = AuthDashboardImport.update({
  path: "/dashboard",
  getParentRoute: () => AuthRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    "/_noauth": {
      id: "/_noauth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof NoauthImport;
      parentRoute: typeof rootRoute;
    };
    "/_auth/dashboard": {
      id: "/_auth/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthDashboardImport;
      parentRoute: typeof AuthImport;
    };
    "/_noauth/signin": {
      id: "/_noauth/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof NoauthSigninImport;
      parentRoute: typeof NoauthImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthRoute: AuthRoute.addChildren({ AuthDashboardRoute }),
  NoauthRoute: NoauthRoute.addChildren({ NoauthSigninRoute }),
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_noauth"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard"
      ]
    },
    "/_noauth": {
      "filePath": "_noauth.tsx",
      "children": [
        "/_noauth/signin"
      ]
    },
    "/_auth/dashboard": {
      "filePath": "_auth/dashboard.tsx",
      "parent": "/_auth"
    },
    "/_noauth/signin": {
      "filePath": "_noauth/signin.tsx",
      "parent": "/_noauth"
    }
  }
}
ROUTE_MANIFEST_END */
